POST http://localhost:8080/post
Content-Type: application/json

{
  "name": "alphaman",
  "job": "crewmate",
  "salary": "100000515"
}

###

GET http://localhost:8080/get

###
PUT http://localhost:8080/put
Content-Type: application/json

{
  "name": "alphaman",
  "job": "crewmate",
  "salary": "100000515"
}

###
DELETE http://localhost:8080/del
Content-Type: application/json

{
  "name": "alphaman",
  "job": "crewmate",
  "salary": "100000515"
}
