POST https://amine-javacrud-nouveau.herokuapp.com/post
Content-Type: application/json

{
  "name": "Spiderman",
  "job": "crewmate",
  "salary": "100000515"
}

###

GET https://amine-javacrud-nouveau.herokuapp.com/

###
PUT https://amine-javacrud-nouveau.herokuapp.com/put
Content-Type: application/json

{
  "name": "Spiderman",
  "job": "crewmate",
  "salary": "100000515"
}

###
DELETE https://amine-javacrud-nouveau.herokuapp.com/del
Content-Type: application/json

{
  "name": "Spiderman",
  "job": "crewmate",
  "salary": "100000515"
}
